### ISSUE TITLE
Passthrough user traffic from ingress to tenant kubernetes clusters

### ISSUE THREAD

**Issue by kvaps** [aenix-io/cozystack#157]
We should consider option to forward user's traffic from parent ingress controller into tenant cluster.

eg. when user has deployed `kubernetes-test0` cluster, we can forward traffic like this:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-test0-workload-ingress
  namespace: tenant-test0
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: tenant-root
  rules:
  - host: example.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-test0-workload-ingress
            port:
              number: 443
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test0-workload-ingress
  namespace: tenant-test0
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    targetPort: 80
  - appProtocol: https
    name: https
    port: 443
    targetPort: 443
  selector:
    cluster.x-k8s.io/cluster-name: kubernetes-test0
```
