### ISSUE TITLE
Provide an opportunity to use single nginx-ingress-controller across all the nodes of the cluster

### ISSUE THREAD

**Issue by kvaps** [aenix-io/cozystack#158]
In this configuration all the nodes can be exposed as separate loadBalancer services with external IPs, eg in addition to `root-ingress-controller` we can create a few more:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: root-ingress-controller-2
  namespace: tenant-root
spec:
  loadBalancerIP: 1.2.3.2 # node 2
  ports:
  - appProtocol: http
    name: http
    port: 80
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: root-ingress-controller-3
  namespace: tenant-root
spec:
  loadBalancerIP: 1.2.3.3 # node 3
  ports:
  - appProtocol: http
    name: http
    port: 80
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```
