### ISSUE TITLE
Apache Kafka load balancers unexpected growth

### ISSUE THREAD

**Issue by velychkovsky** [aenix-io/cozystack#163]
After updating the Apache Kafka application, we've got an issue where the new load balancers count was doubled. Such behavior occurs after updating any parameter. 

**How to reproduce:**

1. Create Managed KAfka Service with the following config:
```
external: true
kafka:
  replicas: 3
  size: "10Gi"
topics:
  - name: "Queue"
    partitions: 24
    replicas: 3
zookeeper:
  replicas: 3
  size: "5Gi"
```

2. Check the count of load balancers (I've got 4)
3. Try to update topic partitions count
4. Deploy kafka with new paramaters
5. Check the count of load balancers (I've got 8)
<img width="1311" alt="image" src="https://github.com/aenix-io/cozystack/assets/32197610/80b53cd1-6609-4cda-a30b-931097d5da50">

The expected behavior is to not update original load balancers
