### ISSUE TITLE
Ambiguous change of ovn networks

### ISSUE THREAD

**Issue by gecube** [aenix-io/cozystack#283]
Hi!

If somebody installs cozy-stack with some kind of configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack
  namespace: cozy-system
data:
  bundle-name: "paas-full"
  ipv4-pod-cidr: "100.64.0.0/16"
  ipv4-pod-gateway: "10.64.0.1"
  ipv4-svc-cidr: "10.65.0.0/16"
  ipv4-join-cidr: "100.66.0.0/16"
```

it gives the broken installation. The pods are mainly running, but ovn is failing. The possible solution could be to change the configmap values to the proper ones like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack
  namespace: cozy-system
data:
  bundle-name: "paas-full"
  ipv4-pod-cidr: "100.64.0.0/16"
  ipv4-pod-gateway: "100.64.0.1"
  ipv4-svc-cidr: "100.65.0.0/16"
  ipv4-join-cidr: "100.66.0.0/16"
```

but unfortunately they are not applied on-the-fly. One needs to remove ovn installation with helm means and reapply it again to make cozystack installation proceed.

I think we should investigate this issue and probably make some warning and / or document workaround.
