### ISSUE TITLE
Make additional validation for CM of cozystack

### ISSUE THREAD

**Issue by gecube** [aenix-io/cozystack#284]
Hi!

Right now it is easy to make a typo when preparing the cozy-stack configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack
  namespace: cozy-system
data:
  bundle-name: "paas-full"
  ipv4-pod-cidr: "100.64.0.0/16"
  ipv4-pod-gateway: "10.64.0.1"
  ipv4-svc-cidr: "10.65.0.0/16"
  ipv4-join-cidr: "100.66.0.0/16"
```

I think it could be beneficial to install before applying some kind of webhook which will check the parameters and write meaningful errors (like "bundle name is not supported") or even switch from CM to our own CRD with a proper schema.

**Comment by mrkhachaturov** [comment]
Something like this?

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cozystacks.cozy-system
spec:
  group: cozy-system
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bundleName:
                  type: string
                  enum:
                    - "paas-full"
                    - "paas-hosted"
                    - "distro-full"
                    - "distro-hosted"
                  description: |
                    The bundle name for the cozystack. Valid options are:
                    - paas-full: PaaS platform, full stack version
                    - paas-hosted: PaaS platform, hosted version
                    - distro-full: Kubernetes distribution, full stack version
                    - distro-hosted: Kubernetes distribution, hosted version
                ipv4PodCidr:
                  type: string
                  pattern: "^([0-9]{1,3}.){3}[0-9]{1,3}/[0-9]+$"
                  description: "The IPv4 Pod CIDR."
                ipv4PodGateway:
                  type: string
                  pattern: "^([0-9]{1,3}.){3}[0-9]{1,3}$"
                  description: "The IPv4 Pod Gateway."
                ipv4SvcCidr:
                  type: string
                  pattern: "^([0-9]{1,3}.){3}[0-9]{1,3}/[0-9]+$"
                  description: "The IPv4 Service CIDR."
                ipv4JoinCidr:
                  type: string
                  pattern: "^([0-9]{1,3}.){3}[0-9]{1,3}/[0-9]+$"
                  description: "The IPv4 Join CIDR."
      additionalPrinterColumns:
        - name: Bundle Name
          type: string
          jsonPath: .spec.bundleName
        - name: Pod CIDR
          type: string
          jsonPath: .spec.ipv4PodCidr
        - name: Pod Gateway
          type: string
          jsonPath: .spec.ipv4PodGateway
        - name: Service CIDR
          type: string
          jsonPath: .spec.ipv4SvcCidr
        - name: Join CIDR
          type: string
          jsonPath: .spec.ipv4JoinCidr
  scope: Namespaced
  names:
    plural: cozystacks
    singular: cozystack
    kind: CozyStack
    shortNames:
    - cs
```
