### ISSUE TITLE
[dashboard] Allow access via nginx-ingress

### ISSUE THREAD

**Issue by kvaps** [aenix-io/cozystack#37]
Some of users trying to use port-forward as persistent method for accessing dashboard, we need to provide them more stable method for accessing dashboard

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: tenant-root
    acme.cert-manager.io/http01-ingress-class: tenant-root
  name: dashboard-ingress
  namespace: cozy-dashboard
spec:
  ingressClassName: tenant-root
  rules:
  - host: demo.cozystack.io
    http:
      paths:
      - backend:
          service:
            name: dashboard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - demo.cozystack.io
    secretName: dashboard-ingress-tls
```
