### ISSUE TITLE
FluxCD CRD's not found | paas-hosted | cluster: kind

### ISSUE THREAD

**Issue by kubebn** [aenix-io/cozystack#425]
Kind config:

```
kind: Cluster
name: kind
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 4443
    protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
```

hosts.tml

```
tee /etc/containerd/certs.d/ghcr.io/hosts.toml > /dev/null <<EOF
server = "https://ghcr.io"

[host."https://ghcr.io"]
  skip_verify = true
```

```
~ ❯ k get po -n cozy-system
NAME                         READY   STATUS    RESTARTS      AGE
cozystack-85c98969bd-jl95x   2/2     Running   3 (84s ago)   4m46s
~ ❯ k get po -n cozy-fluxcd
NAME                             READY   STATUS    RESTARTS   AGE
flux-operator-5975cd5785-jgf8l   1/1     Running   0          4m53s
~ ❯ k get ns
NAME                             STATUS   AGE
cozy-cert-manager                Active   4m59s
cozy-clickhouse-operator         Active   4m59s
cozy-dashboard                   Active   4m59s
cozy-etcd-operator               Active   4m59s
cozy-fluxcd                      Active   4m59s
cozy-grafana-operator            Active   4m59s
cozy-kafka-operator              Active   4m59s
cozy-linstor                     Active   4m59s
cozy-mariadb-operator            Active   4m59s
cozy-monitoring                  Active   4m58s
cozy-postgres-operator           Active   4m58s
cozy-public                      Active   4m58s
cozy-rabbitmq-operator           Active   4m58s
cozy-redis-operator              Active   4m58s
cozy-system                      Active   5m1s
cozy-telepresence                Active   4m58s
cozy-victoria-metrics-operator   Active   4m58s
default                          Active   8m15s
kube-node-lease                  Active   8m15s
kube-public                      Active   8m15s
kube-system                      Active   8m15s
local-path-storage               Active   8m12s
```

Logs:

https://paste.openstack.org/show/bUUOqafS7FF3zcLVqGyo/

If containerdConfigPatches are not configured, ErrImagePullBackoff appears.

**Comment by kingdonb** [comment]
Do you have someone intercepting ghcr.io or are you air-gapped - I see this error which explains why the manifests did not load:

```
{"level":"error","ts":"2024-10-15T11:20:10.492Z","msg":"Reconciler error","controller":"fluxinstance","controllerGroup":"fluxcd.controlplane.io","controllerKind":"FluxInstance","FluxInstance":{"name":"flux","namespace":"cozy-fluxcd"},"namespace":"cozy-fluxcd","name":"flux","reconcileID":"baf22973-b379-46cd-bc68-c045ede01252","error":"pulling artifact oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest failed: Get \"https://ghcr.io/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
```

There is a configuration variable that you can use if you crane lift copied `controlplaneio-fluxcd/flux-operator-manifests:latest` into your local ghcr mirror, which might be the next step if you tell me that you are air-gapped

(I haven't tested this configuration in an air-gap)

Note this section in the `cozy-fluxcd` namespace `FluxInstance` named `flux`:

```
spec:
  cluster:
    # ...
  components:
    # ...
  distribution:
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest
    registry: ghcr.io/fluxcd
    version: 2.3.x
```

These are the defaults. To install Flux, this needs to point at an OCI registry with the `latest` artifact, or some specific version of the packaged Flux manifests that you find at:

https://github.com/controlplaneio-fluxcd/flux-operator/pkgs/container/flux-operator-manifests
