### ISSUE TITLE
Fix tolerations in charts

### ISSUE THREAD

**Issue by gecube** [aenix-io/cozystack#92]
https://github.com/aenix-io/cozystack/blob/b838ee5729008fdd2192e572549637353ea612f2/packages/apps/kubernetes/templates/csi/deploy.yaml#L24

add

```yaml
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: "NoSchedule"
```

to the list of tolerations.

Also check all other charts for the same issue.
